In [1]:
# 1 step: Inport libraries

import pandas as pd
import numpy as np
! pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in C:\Users\kumar\AppData\Roaming\Python\Python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\kumar\AppData\Roaming\Python\Python313\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# step 2: Load Dataset:
df = pd.read_excel('Churn_Unclean_Project.xlsx')

In [3]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            542 non-null    str
 1   Customer_Name          533 non-null    str
 2   Gender                 536 non-null    str
 3   Age                    536 non-null    float64
 4   State                  531 non-null    str
 5   City                   539 non-null    str
 6   Tenure_Months          534 non-null    float64
 7   Subscription_Type      530 non-null    str
 8   Monthly_Charges        529 non-null    float64
 9   Total_Charges          533 non-null    float64
 10  Contract_Type          538 non-null    str
 11  Payment_Method         526 non-null    str
 12  Internet_Service       535 non-null    str
 13  Tech_Support           530 non-null    str
 14  Senior_Citizen         534 non-null    str
 15  Dependents             539 non-null    str
 16  Churn                  538 non-null    str
 17  Last_Interaction_Date  539 non-null    str
dtypes: float64(4), str(14)
memory usage: 120.0 KB

In [5]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

In [6]:
df.shape

(542, 18)

In [7]:
# step 4: check missing value:
df.isnull().sum()

Customer_ID               0
Customer_Name             9
Gender                    6
Age                       6
State                    11
City                      3
Tenure_Months             8
Subscription_Type        12
Monthly_Charges          13
Total_Charges             9
Contract_Type             4
Payment_Method           16
Internet_Service          7
Tech_Support             12
Senior_Citizen            8
Dependents                3
Churn                     4
Last_Interaction_Date     3
dtype: int64

In [8]:
# step 5: Check Duplicate Record:
df.duplicated().sum()

np.int64(7)

In [10]:
# Remove Duplicates:
df.drop_duplicates(inplace=True)

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.shape

(535, 18)

In [13]:
# step 7: Replace Dirty Values:
df.replace(['N/A','NULL','',' '],np.nan,inplace=True)

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,C5005,Sneha Jain,Female,115.0,Gujarat,Surat,1.0,NaN,1633.64,1707.64,Two Year,Debit Card,Cable,No,No,Yes,No,13-03-2026
538,C5006,Neha Verma,Female,18.0,Delhi,Noida,70.0,Standard,2008.83,140376.10,Month-to-Month,UPI,DSL,Yes,No,No,No,26-12-2025
539,C5007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,One Year,Cash,Cable,Yes,Yes,Yes,No,14-01-2025
540,C5008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,BASIC,1200.00,75799.15,Two Year,NaN,Fiber,Yes,No,No,No,28-02-2025
541,C5009,Rahul Singh,Male,25.0,UP,Kanpur,30.0,Basic,1341.52,NaN,Month-to-Month,Credit Card,Cable,No,No,Yes,No,29-11-2025

In [16]:
# step 7: Remove Extra Space:

df=df.apply(lambda x:x.str.strip() if x.dtype=="object" else x)

In [22]:
# step 8: Proper Case:

df['Customer_Name']=df['Customer_Name'].str.title()
df['State']=df['State'].str.title()
df['City']=df['City'].str.title()
df['Custom']=df['Customer_Name'].str.title()
df['Customer_Name']=df['Customer_Name'].str.title()
df["Churn"]=df['Churn'].str.title()
df["Gender"]=df["Gender"].str.title()

In [23]:
df["Subscription_Type"].value_counts()

Subscription_Type
Premium      180
Standard     168
Basic        165
Premium        3
basic          2
BASIC          2
Premium        1
Basic          1
Standard       1
  Basic        1
Name: count, dtype: int64

In [21]:
df["Churn"].value_counts()

Churn
No     405
Yes    127
Name: count, dtype: int64

In [25]:
# 10 :Convert Numeric column

cols = ["Age","Tenure_Months","Monthly_Charges","Total_Charges"]

for c in cols:
    df[c] = pd.to_numeric(df[c],errors="coerce")

In [26]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  529.000000     528.000000       523.000000     527.000000
mean    44.328922      36.518939      1329.967285   49739.683890
std     18.635396      20.659332       713.450173   41633.677902
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       757.420000   18818.270000
50%     44.000000      38.000000      1295.880000   40649.600000
75%     57.000000      54.000000      1879.020000   75126.770000
max    165.000000      72.000000      2492.510000  171429.830000

In [27]:
# 11 : Remove Invalid Age:
df = df[(df['Age']>18) & (df['Age']<=100)]

In [28]:
# 12 : Remove Negative Charges:
df=df[df["Monthly_Charges"]>=0]
df=df[df["Total_Charges"]>=0]

In [29]:
df.shape

(475, 19)

In [30]:
# 13 Date Conversion
df["Last_Interaction_Date"]=pd.to_datetime(df["Last_Interaction_Date"],errors='coerce')

In [35]:
# Option 1: Assign back (recommended)
df["Tech_Support"]   = df["Tech_Support"].fillna("No")
df["Payment_Method"] = df["Payment_Method"].fillna("Unknown")
df["Monthly_Charges"] = df["Monthly_Charges"].fillna(df["Monthly_Charges"].mean())
df["Tenure_Months"]  = df["Tenure_Months"].fillna(df["Tenure_Months"].mean())
df["Age"]            = df["Age"].fillna(df["Age"].mean())

In [45]:
# Corrected fill for Last_Interaction_Date
df["Last_Interaction_Date"] = df["Last_Interaction_Date"].fillna(df["Last_Interaction_Date"].median())

In [46]:
# 15 Feature Engineering:

# customer Lifetime Value

df['Customer_Value']=df["Monthly_Charges"]*df["Tenure_Months"]

In [47]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,...,Senior_Citizen,Dependents,Churn,Last_Interaction_Date,Custom,Customer_Value,Monthly_Revenue,Tenure_Group,Senior_Flag,Churn_Flag
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,...,No,Yes,No,2025-12-10,Abhishek Jaiswal,93627.08,1614.26,49-72 month,Adult,0.0
2,C1002,Pooja Singh,Female,42.0,Up,Kanpur,13.0,Basic,555.03,6869.39,...,No,No,Yes,2025-08-10,Pooja Singh,7215.39,555.03,13-24 month,Adult,1.0
4,C1004,Mohit Arora,Male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,...,No,No,No,2026-02-04,Mohit Arora,1884.12,314.02,0-12 month,Adult,0.0
7,C1007,Vikas Yadav,Male,61.0,Delhi,NaN,57.0,Basic,2196.18,125145.26,...,Yes,Yes,No,2025-08-10,Vikas Yadav,125182.26,2196.18,49-72 month,Senior,0.0
8,C1008,Mohit Arora,Male,45.0,Gujarat,Ahmedabad,63.0,BASIC,1200.00,75799.15,...,No,No,No,2025-08-10,Mohit Arora,75600.00,1200.00,49-72 month,Adult,0.0

In [48]:
# Monthly Revenue:

df["Monthly_Revenue"]=df["Monthly_Charges"]

In [39]:
# Tenure Group "0-12","13-24","25-48","49-72"
bins=[0,12,24,48,72]
label=labels=["0-12 month","13-24 month","25-48 month","49-72 month"]

df['Tenure_Group']=pd.cut(df["Tenure_Months"],bins=bins,labels=label)

In [40]:
# Senior Citizen Flag

df['Senior_Flag']=np.where(df["Age"]>60,"Senior","Adult")

In [41]:
# Churn Flag

df["Churn_Flag"]=df["Churn"].map({"Yes":1,"No":0})

In [49]:
df.info()

<class 'pandas.DataFrame'>
Index: 475 entries, 0 to 540
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            475 non-null    str
 1   Customer_Name          471 non-null    str
 2   Gender                 471 non-null    str
 3   Age                    475 non-null    float64
 4   State                  468 non-null    str
 5   City                   470 non-null    str
 6   Tenure_Months          475 non-null    float64
 7   Subscription_Type      470 non-null    str
 8   Monthly_Charges        475 non-null    float64
 9   Total_Charges          475 non-null    float64
 10  Contract_Type          473 non-null    str
 11  Payment_Method         475 non-null    str
 12  Internet_Service       470 non-null    str
 13  Tech_Support           475 non-null    str
 14  Senior_Citizen         469 non-null    str
 15  Dependents             474 non-null    str
 16  Churn                  473 non-null    str
 17  Last_Interaction_Date  475 non-null    datetime64[us]
 18  Custom                 471 non-null    str
 19  Customer_Value         475 non-null    float64
 20  Monthly_Revenue        475 non-null    float64
 21  Tenure_Group           475 non-null    category
 22  Senior_Flag            475 non-null    str
 23  Churn_Flag             473 non-null    float64
dtypes: category(1), datetime64[us](1), float64(7), str(15)
memory usage: 130.8 KB

In [50]:
df.describe()

,Age,Tenure_Months,Monthly_Charges,Total_Charges,Last_Interaction_Date,Customer_Value,Monthly_Revenue,Churn_Flag
count,475.000000,475.000000,475.000000,475.000000,475,475.000000,475.000000,473.000000
mean,44.092632,35.951064,1348.259137,49719.436800,2025-08-27 02:07:19.578947,49579.904821,1348.259137,0.238901
min,19.000000,1.000000,302.540000,354.120000,2025-01-01 00:00:00,379.700000,302.540000,0.000000
25%,32.000000,19.000000,758.985000,18954.440000,2025-08-10 00:00:00,18873.545000,758.985000,0.000000
50%,44.000000,37.000000,1289.210000,39950.000000,2025-08-10 00:00:00,40402.000000,1289.210000,0.000000
75%,56.500000,53.000000,1876.635000,72963.600000,2025-08-10 00:00:00,72841.050000,1876.635000,0.000000
max,70.000000,72.000000,2492.510000,171429.830000,2026-12-06 00:00:00,171658.830000,2492.510000,1.000000
std,14.904472,20.243969,652.471568,38993.097527,NaN,38872.381304,652.471568,0.426863

In [51]:
# 17 CSV Clean Dataset

df.to_csv("Clean_Churn_Data.csv",index=False)

In [52]:
# Export into MySQl

from sqlalchemy import create_engine

engine=create_engine("mysql+pymysql://root:msvinod3827#@localhost/churndb")

In [54]:
df.to_sql(
    name="customer_churn",
    con=engine,
    if_exists="replace",
    index=False
)

475